version: '2'
services:
    syslog-ng:
        build: .
        image: [imageId]
        volumes:
            - ./syslog-ng/server.conf:/etc/syslog-ng/syslog-ng.conf
            - ./log:/var/log
        ports:
            - "514:514" #udp
            - "601:601" #tcp
        links:
            - "elk"
        depends_on:
            - "elk"
    elk:
        image: [imageId]
        volumes:
            - ./logstash:/etc/logstash/conf.d
            - ./log:/var/log
        ports:
            - "5601:5601" #kibana
            - "9200:9200" #elastic
            - "5044:5044" #logstash